name: MiniGameFramework
main: net.milocodee.minigame.MiniGamePlugin
version: 1.0
api-version: 1.21
authors: ["Milo"]
commands:
  startminigame:
    description: Force-start a minigame (Admin)
    permission: minigame.start
  joingame:
    description: Join the lobby
permissions:
  minigame.start:
    description: Allows starting the minigame
    default: op
